# Generated by Django 3.2.6 on 2021-08-22 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('num_operations', models.IntegerField()),
                ('value_token', models.IntegerField()),
            ],
        ),
    ]
